url: https://github.com/vignesh-narayanan-sfdc/
baseurl: /sgs.github.io

# Site settings
title: SGS Constructions
email: your-email@domain.com
description: "SGS Real Estate Constructions. Renovation Services. High quality affordable homes in Coimbatore."


# Team names, titles and social links
people:
- name: Mohana Kannan
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Vadavalli
  - line: Coimbatore, Tamil Nadu

# Build settings
markdown: kramdown
permalink: pretty